version: "3"

services:
  backend:
    build: ./morpherApp
    restart: always

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "5566:443"
    volumes:
      - ${CERTS_DIR}:/data/certs/:ro
    env_file:
      - ./.env

